apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: api
  namespace: argocd
  labels:
    env: dev
    type: project
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: '*'
    server: '*'
  sourceRepos:
  - '*'