apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginix
  namespace: argocd
  labels:
    env: dev
    type: helm
spec:
  project: nginix
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: nginx
    targetRevision: 13.1.4
    helm:
      values:
        service:
          type: LoadBalancer
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
